name: idchats_flutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-417.4.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_inner_drawer: 
    git: 
      url: https://github.com/tianxiaotouyuna/flutter_inner_drawer
      ref: master
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  dartz: ^0.10.1
  http: ^0.13.3
  get_it: ^7.2.0
  shared_preferences: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/html/
    - assets/i8n/
    - assets/images/
